FROM centos:7

ARG VERSION=3.28

RUN yum install docker curl wget java-1.8.0-openjdk git openssh-client openssl procps -y \
    && curl --create-dirs -sSLo /usr/share/jenkins/slave.jar https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/${VERSION}/remoting-${VERSION}.jar

COPY --from=cnych/jenkins:jnlp /usr/local/bin/jenkins-slave /usr/local/bin/jenkins-slave

ENTRYPOINT ["jenkins-slave"]
